#!/bin/sh
set -o errexit -o nounset -o pipefail

if [ -z "${SLACK_URL-}" ]; then
	echo "SLACK_URL recipient required"
	exit 1
fi

alertmanager_cfg="$1"

cat > "$alertmanager_cfg" << EOF
route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        username: 'Prometheus'
        channel: '#customer-audioburst'
        api_url: '$SLACK_URL'
EOF
